typography_spectrum: 0.12237965851090848
content_rating:
  adult: false
color:
  brandStrength: 0.49644097755663097
  lightness: 0.656527888495475
  saturation: 0.27616546559147537
  rhythmicContrast: 0.22938845795579255
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
github: true
layout_spectrum: 0.24126001098193228
logo: null
name: My Blog
navigation:
  - url: 'http://www.theminimalists.com/game/'
    name: Minimalists
    type: external
  - name: Home
    url: 'http://jordy.help'
    type: external
  - name: Art
    url: 'http://art.jordy.help'
    type: external
  - url: 'http://www.theminimalists.com/minimalism/'
    name: Minimalists
    type: external
favicon: null
title: Jordy's Blog
content: []
coverPrefs:
  filter: false
description: A blog about things and having less of them
purpose: []
